{
  config,
  pkgs,
  ...
}:
{
  imports = [
    ./auto-save.nix
    ./auto-session.nix
    ./blink.nix
    ./better-escape.nix
    ./cmp.nix
    ./conform.nix
    ./colorizer.nix
    ./copilot.nix
    ./git-conflict.nix
    ./lsp.nix
    ./lspkind.nix
    ./lualine.nix
    ./luasnip.nix
    ./indent-blankline.nix
    ./noice.nix
    ./treesitter.nix
    ./nvim-autopairs.nix
    ./trouble.nix
  ];
}
